version: "3.9"

services:
  api:
    build: .
    container_name: vision_gestao_api
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=vision_gestao
    restart: always

  db:
    image: postgres:15
    container_name: vision_gestao_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vision_gestao
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
